# Generated by Django 2.0.5 on 2018-06-08 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('Is_Question_of', models.IntegerField()),
                ('Question_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Original_Question', models.CharField(max_length=250)),
                ('Short_Question', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('Questionnaire_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Questionnaire_label', models.CharField(max_length=250)),
                ('Questionnaire_note', models.CharField(max_length=250)),
                ('Questionnaire_title', models.CharField(max_length=250)),
                ('Questionnaire_publication_year', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='Questionnaire_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_display.Type'),
        ),
        migrations.AddField(
            model_name='question',
            name='Question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_display.Questionnaire'),
        ),
        migrations.AddField(
            model_name='question',
            name='Question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_display.Type'),
        ),
    ]
