# Generated by Django 2.0.5 on 2018-06-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_display', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='changes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetUri', models.CharField(max_length=300)),
                ('attributeName', models.CharField(max_length=300)),
                ('oldValue', models.CharField(max_length=300)),
                ('newValue', models.CharField(max_length=300)),
                ('dateCreated', models.DateField()),
                ('dateModified', models.DateField()),
                ('userId', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='Question_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='Question_type',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='Questionnaire_type',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Questionnaire',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
