# Generated by Django 2.0.5 on 2018-06-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_display', '0002_auto_20180618_1523'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='changes',
            new_name='change',
        ),
    ]
