# Generated by Django 2.0.5 on 2018-06-20 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_display', '0004_auto_20180620_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='userIdentification',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='change',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_display.userIdentification'),
        ),
    ]
