# Generated by Django 2.0.5 on 2018-06-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_display', '0005_auto_20180620_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='userId',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='userIdentification',
        ),
    ]
