# Generated by Django 2.0.5 on 2018-06-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_display', '0006_auto_20180620_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change',
            name='id',
        ),
        migrations.AlterField(
            model_name='change',
            name='dateCreated',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='change',
            name='dateModified',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='change',
            name='targetUri',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='change',
            name='userId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
