# Generated by Django 2.0.5 on 2018-06-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_display', '0007_auto_20180620_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='changes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetUri', models.URLField(max_length=300)),
                ('attributeName', models.CharField(max_length=200)),
                ('oldValue', models.CharField(max_length=200)),
                ('newValue', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='change',
        ),
    ]
