# Generated by Django 2.0.5 on 2018-06-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_display', '0009_auto_20180629_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changes',
            options={'verbose_name_plural': 'changes'},
        ),
    ]
