# Generated by Django 2.0.5 on 2018-07-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_display', '0010_auto_20180629_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
